=== silvia-llorente/hipams/files/ISOIEC_23092-3_Annex_A5_aupr_schema_SL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="urn:mpeg:mpeg-g:protection:access-unit:2019"
    xmlns:aupr="urn:mpeg:mpeg-g:protection:access-unit:2019"
    xmlns:xacml="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17"
    xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">
    <xs:import namespace="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17"
        schemaLocation="http://docs.oasis-open.org/xacml/3.0/xacml-core-v3-schema-wd-17.xsd"/>
    <xs:import namespace="http://www.w3.org/2000/09/xmldsig#"
        schemaLocation="https://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd#"/>
    <xs:complexType name="AccessUnitEncryptionParametersType">
        <xs:sequence>
            <xs:element name="wrappedKey" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:base64Binary">
                            <xs:attribute name="configurationID" type="xs:int" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="cipher">
                <xs:simpleType>
                    <xs:restriction base="xs:anyURI">
                        <xs:enumeration value="urn:mpeg:mpeg-g:protection:aes128-ctr"/>
                        <xs:enumeration value="urn:mpeg:mpeg-g:protection:aes192-ctr"/>
                        <xs:enumeration value="urn:mpeg:mpeg-g:protection:aes256-ctr"/>
                        <xs:enumeration value="urn:mpeg:mpeg-g:protection:aes128-gcm"/>
                        <xs:enumeration value="urn:mpeg:mpeg-g:protection:aes192-gcm"/>
                        <xs:enumeration value="urn:mpeg:mpeg-g:protection:aes256-gcm"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:base64Binary" name="aublockIV"/>
            <xs:element type="xs:base64Binary" name="auinIV" minOccurs="0"/>
            <xs:element type="xs:base64Binary" name="aublockTAG" minOccurs="0"/>
            <xs:element type="xs:base64Binary" name="auinTAG" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SignatureType">
        <xs:sequence>
            <xs:element ref="ds:Signature"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="AccessUnitProtectionType">
        <xs:sequence>
            <xs:element type="aupr:AccessUnitEncryptionParametersType" name="AccessUnitEncryptionParameters" minOccurs="0" maxOccurs="1"/>
            <xs:element type="aupr:SignatureType" name="SignatureParameters" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="AccessUnitProtection" type="aupr:AccessUnitProtectionType"/>
</xs:schema>

=== silvia-llorente/hipams/volumes/hcs/storage/2/dg_1/dt_1/patient_1/patient_pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<AccessUnitProtection xmlns="urn:mpeg:mpeg-g:protection:access-unit:2019" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:mpeg-g:protection:access-unit:2019 /opt/HCService/schemas/ISOIEC_23092-3_Annex_A5_aupr_schema_SL.xsd">
    <AccessUnitEncryptionParameters>
	<wrappedKey configurationID="19">oKHivMEITYK7mSbuVK4KpaDrs1J7q/3gQdCImTryynzx0QzHS4ydQQ==</wrappedKey>
        <cipher>urn:mpeg:mpeg-g:protection:aes256-gcm</cipher>
        <aublockIV>AAECAwQFBgcICQoL</aublockIV>
        <aublockTAG>MTIzNDU2Nzg5MGFiY2RlZg==</aublockTAG>
       <auinIV>cXJzdHV2d3h5ejAx</auinIV>
       <auinTAG>cXJzdHV2d3h5ejAx</auinTAG>
    </AccessUnitEncryptionParameters>
</AccessUnitProtection>

=== silvia-llorente/hipams/files/dg_0-xml-pruebas/dg_1_KeyDerivation_AES-CTR/au_pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<AccessUnitProtection xmlns="urn:mpeg:mpeg-g:protection:access-unit:2019" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:mpeg-g:protection:access-unit:2019 C:\test\resources\schemas\ISOIEC_23092-3_Annex_A5_aupr_schema_SL.xsd">
  
  <AccessUnitEncryptionParameters>
			<wrappedKey configurationID="1">QmFzZTY0V3JhcHBlZEtleQ==</wrappedKey>
			<cipher>urn:mpeg:mpeg-g:protection:aes256-gcm</cipher>
			<aublockIV>AAECAwQFBgcICQoL</aublockIV>
			<auinIV>cXJzdHV2d3h5ejAx</auinIV>
			<aublockTAG>MTIzNDU2Nzg5MGFiY2RlZg==</aublockTAG>
			<auinTAG>cXJzdHV2d3h5ejAx</auinTAG>
			
		</AccessUnitEncryptionParameters>
		
</AccessUnitProtection>
