=== silvia-llorente/hipams/files/ISOIEC_23092-3_Annex_A4_dtpr_schema_SL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="urn:mpeg:mpeg-g:protection:dataset:2019"
    xmlns:dtpr="urn:mpeg:mpeg-g:protection:dataset:2019"
    xmlns:xacml="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" 
    xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">
    <xs:import namespace="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17"
        schemaLocation="http://docs.oasis-open.org/xacml/3.0/xacml-core-v3-schema-wd-17.xsd"/>
    <xs:import namespace="http://www.w3.org/2000/09/xmldsig#"
        schemaLocation="https://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd#"/>    
        <xs:complexType name="KeySymmetricWrapType">
            <xs:sequence>
                <xs:element type="xs:string" name="kek"/>
                <xs:element type="xs:base64Binary" name="wrappedKey"/>
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="KeyAsymmetricWrapType">
            <xs:sequence>
                <xs:element name="hashFunction">
                    <xs:simpleType>
                        <xs:restriction base="xs:anyURI">
                            <xs:enumeration value="urn:mpeg:mpeg-g:protection:sha224"/>
                            <xs:enumeration value="urn:mpeg:mpeg-g:protection:sha256"/>
                            <xs:enumeration value="urn:mpeg:mpeg-g:protection:sha384"/>
                            <xs:enumeration value="urn:mpeg:mpeg-g:protection:sha512"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="maskGenerationHashFunction">
                    <xs:simpleType>
                        <xs:restriction base="xs:anyURI">
                            <xs:enumeration value="urn:mpeg:mpeg-g:protection:sha224"/>
                            <xs:enumeration value="urn:mpeg:mpeg-g:protection:sha256"/>
                            <xs:enumeration value="urn:mpeg:mpeg-g:protection:sha384"/>
                            <xs:enumeration value="urn:mpeg:mpeg-g:protection:sha512"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element type="xs:string" name="publicKeyName"/>
                <xs:element type="xs:base64Binary" name="wrappedKey"/>
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="KeyDerivationType">
            <xs:sequence>
                <xs:element name="PRF">
                    <xs:simpleType>
                        <xs:restriction base="xs:anyURI">
                            <xs:enumeration value="urn:mpeg:mpeg-g:protection:hmac-sha224"/>
                            <xs:enumeration value="urn:mpeg:mpeg-g:protection:hmac-sha256"/>
                            <xs:enumeration value="urn:mpeg:mpeg-g:protection:hmac-sha384"/>
                            <xs:enumeration value="urn:mpeg:mpeg-g:protection:hmac-sha512"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element type="xs:string" name="passwordName"/>
                <xs:element type="xs:base64Binary" name="salt"/>
                <xs:element type="xs:integer" name="iterations"/>
                <xs:element type="xs:integer" name="length"/>
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="KeyTransportType">
            <xs:sequence>
                <xs:element type="xs:string" name="keyName"/>
                <xs:choice>
                    <xs:element type="dtpr:KeyDerivationType" name="KeyDerivation"/>
                    <xs:element type="dtpr:KeySymmetricWrapType" name="KeySymmetricWrap"/>
                    <xs:element type="dtpr:KeyAsymmetricWrapType" name="KeyAsymmetricWrap"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
        <xs:simpleType name="CipherURIType">
            <xs:restriction base="xs:anyURI">
                <xs:enumeration value="urn:mpeg:mpeg-g:protection:aes128-ctr"/>
                <xs:enumeration value="urn:mpeg:mpeg-g:protection:aes192-ctr"/>
                <xs:enumeration value="urn:mpeg:mpeg-g:protection:aes256-ctr"/>
                <xs:enumeration value="urn:mpeg:mpeg-g:protection:aes128-gcm"/>
                <xs:enumeration value="urn:mpeg:mpeg-g:protection:aes192-gcm"/>
                <xs:enumeration value="urn:mpeg:mpeg-g:protection:aes256-gcm"/>
            </xs:restriction>
        </xs:simpleType>
        <xs:complexType name="EncryptionParametersType">
            <xs:sequence>
                <xs:element name="cipher" type="dtpr:CipherURIType" minOccurs="0"/>
                <xs:element type="xs:string" name="keyName"/>
                <xs:element type="xs:base64Binary" name="IV" minOccurs="0"/>
                <xs:element type="xs:base64Binary" name="TAG" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute name="encryptedLocations" type="xs:anyURI" use="required"/>
            <xs:attribute name="configurationID" type="xs:integer"/>
        </xs:complexType>
        <xs:complexType name="SignatureType">
            <xs:sequence>
                <xs:element ref="ds:Signature"/>
            </xs:sequence>
        </xs:complexType>
        <xs:complexType name="DatasetProtectionType">
            <xs:sequence>
                <xs:element type="dtpr:KeyTransportType" name="KeyTransportAES" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element type="dtpr:EncryptionParametersType" name="EncryptionParameters" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element type="dtpr:SignatureType" name="SignatureParameters" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="xacml:Policy" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    <xs:element name="DatasetProtection" type="dtpr:DatasetProtectionType"/>
</xs:schema>

=== silvia-llorente/hipams/volumes/hcs/storage/2/dg_1/dt_1/dt_pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<DatasetProtection xmlns="urn:mpeg:mpeg-g:protection:dataset:2019" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"       
    xsi:schemaLocation="urn:mpeg:mpeg-g:protection:dataset:2019 /opt/HCService/schemas/ISOIEC_23092-3_Annex_A4_dtpr_schema_SL.xsd">    <KeyTransportAES>
        <keyName>TransportKey1</keyName>
        <KeySymmetricWrap>
            <kek>PnJzYXsZxPtLvXqIXNyCTxxL4OIf/tvdxF8V8GhMJ4Q=</kek>
            <wrappedKey>3auMNGGPxn/FiwL6rOpTwf58cro87gTd3uBOjs6LQcmnvIoRN6IyFg==</wrappedKey>
        </KeySymmetricWrap>
    </KeyTransportAES>
    <EncryptionParameters encryptedLocations="metadata" configurationID="19">
        <cipher>urn:mpeg:mpeg-g:protection:aes256-gcm</cipher>
        <keyName>TransportKey1</keyName>
        <IV>510M2JtNMU5yDxLH</IV>
        <TAG>0VKqcvcAiBcAWxvsEeHRKA==</TAG>
    </EncryptionParameters>

</DatasetProtection>

=== silvia-llorente/hipams/files/dg_0-xml-pruebas/dg_1_KeyDerivation_AES-CTR/dt_pr.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<DatasetProtection xmlns="urn:mpeg:mpeg-g:protection:dataset:2019" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xacml="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:mpeg-g:protection:dataset:2019 C:\test\resources\schemas\ISOIEC_23092-3_Annex_A4_dtpr_schema_SL.xsd">
   
   <KeyTransportAES>
    <keyName>DerivedKey1</keyName>
    <KeyDerivation>
      <PRF>urn:mpeg:mpeg-g:protection:hmac-sha256</PRF>
      <salt>a1b2c3d4e5==</salt>
      <iterations>10000</iterations>
      <length>32</length>
    </KeyDerivation>
  </KeyTransportAES>
  <EncryptionParameters encryptedLocations="metadata" configurationID="1">
    <cipher>urn:mpeg:mpeg-g:protection:aes128-ctr</cipher>
    <keyName>DerivedKey1</keyName>
    <!-- IV es opcional en CTR, pero aquÃ­ lo incluimos -->
    <IV>AAECAwQFBgcICQoL</IV>
  </EncryptionParameters>

   
</DatasetProtection>
